// src/app/features/auth/login/login.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { AuthService } from '../../../core/services/auth.service';
import { Toast } from 'primeng/toast';
import { MessageService } from 'primeng/api';
import { LucideAngularModule, ArrowRight, Eye, EyeOff, Sparkles } from 'lucide-angular';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, RouterModule, ReactiveFormsModule, Toast, LucideAngularModule],
  providers: [MessageService],
  template: `
    <div class="min-h-screen flex items-center justify-center bg-[var(--surface)] p-6 relative overflow-hidden">
      <!-- Background Decorative Elements -->
      <div class="absolute top-0 left-0 w-full h-full opacity-[0.03] pointer-events-none" style="background-image:linear-gradient(var(--brand-dark) 1px,transparent 1px),linear-gradient(90deg,var(--brand-dark) 1px,transparent 1px);background-size:40px 40px"></div>
      <div class="absolute -top-24 -right-24 w-96 h-96 bg-[var(--brand-gold)] opacity-[0.05] rounded-full blur-3xl"></div>
      <div class="absolute -bottom-24 -left-24 w-96 h-96 bg-[var(--brand-dark)] opacity-[0.05] rounded-full blur-3xl"></div>

      <div class="w-full max-w-sm bg-white rounded-[var(--radius-lg)] shadow-2xl border border-[var(--border)] relative z-10 overflow-hidden animate-slide-up">
        <div class="p-6 sm:p-8">
          <!-- Logo -->
          <div class="flex flex-col items-center gap-2 mb-6">
            <div class="w-10 h-10 bg-[var(--brand-dark)] rounded-2xl flex items-center justify-center shadow-lg">
              <lucide-angular [img]="SparklesIcon" class="w-4 h-4 text-[var(--brand-gold)]"></lucide-angular>
            </div>
            <div class="text-center">
              <span class="text-lg font-black tracking-[0.25em] uppercase text-[var(--brand-dark)]">SkinTone</span>
              <span class="text-lg luxury-font italic text-[var(--brand-gold)] ml-1">AI</span>
            </div>
          </div>

          <!-- Heading -->
          <div class="text-center space-y-1 mb-5">
            <h1 class="text-xl luxury-font text-[var(--brand-dark)]">Welcome Back</h1>
            <p class="text-[8px] uppercase tracking-[0.3em] text-[var(--muted)] font-bold">Access Your Style Profile</p>
          </div>

          <!-- Form -->
          <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="space-y-3.5">
            <div class="space-y-1">
              <label class="text-[9px] font-black tracking-[0.2em] uppercase text-[var(--muted)] px-1">Email Address</label>
              <div class="relative group">
                <input type="email" formControlName="email" placeholder="your@email.com" 
                  class="w-full bg-[var(--surface)] border-2 border-transparent rounded-[var(--radius-md)] px-5 py-3.5 text-sm focus:border-[var(--brand-gold)] focus:bg-white transition-all outline-none">
              </div>
            </div>

            <div class="space-y-1">
              <label class="text-[9px] font-black tracking-[0.2em] uppercase text-[var(--muted)] px-1">Password</label>
              <div class="relative group">
                <input [type]="showPw ? 'text' : 'password'" formControlName="password" placeholder="••••••••" 
                  class="w-full bg-[var(--surface)] border-2 border-transparent rounded-[var(--radius-md)] px-5 py-3.5 text-sm focus:border-[var(--brand-gold)] focus:bg-white transition-all outline-none pr-12">
                <button type="button" (click)="showPw = !showPw" class="absolute right-4 top-1/2 -translate-y-1/2 text-[var(--muted)] hover:text-[var(--brand-dark)]">
                  <lucide-angular [img]="showPw ? EyeOffIcon : EyeIcon" class="w-4 h-4"></lucide-angular>
                </button>
              </div>
            </div>

            <div *ngIf="error" class="bg-red-50 border border-red-100 rounded-xl px-4 py-3 animate-fade-in">
              <p class="text-[10px] font-bold text-red-600 uppercase tracking-widest text-center">{{ error }}</p>
            </div>

            <button type="submit" [disabled]="loginForm.invalid || isLoading" 
              class="w-full bg-[var(--brand-dark)] text-white rounded-[var(--radius-md)] py-4 text-[11px] font-black uppercase tracking-[0.3em] shadow-xl hover:bg-[var(--brand-dark-soft)] active:scale-[0.98] transition-all disabled:opacity-30 flex items-center justify-center gap-3">
              <i *ngIf="isLoading" class="pi pi-spin pi-spinner"></i>
              <span>{{ isLoading ? 'Processing...' : 'Secure Sign In' }}</span>
              <lucide-angular *ngIf="!isLoading" [img]="ArrowIcon" class="w-4 h-4"></lucide-angular>
            </button>
          </form>

          <!-- Divider -->
          <div class="flex items-center gap-4 my-6">
            <div class="flex-1 h-px bg-[var(--border)]"></div>
            <span class="text-[8px] uppercase tracking-[0.3em] text-[var(--muted)] font-black">Or Join Us</span>
            <div class="flex-1 h-px bg-[var(--border)]"></div>
          </div>

          <!-- Socials (Mock) -->
          <div class="grid grid-cols-2 gap-3 mb-6">
            <button class="flex items-center justify-center gap-2 py-3 rounded-xl border border-[var(--border)] text-[9px] uppercase tracking-widest font-black text-[var(--brand-dark)] hover:bg-[var(--surface)] transition-all">
              Google
            </button>
            <button class="flex items-center justify-center gap-2 py-3 rounded-xl border border-[var(--border)] text-[9px] uppercase tracking-widest font-black text-[var(--brand-dark)] hover:bg-[var(--surface)] transition-all">
              Apple
            </button>
          </div>

          <!-- Footer Link -->
          <p class="text-center text-[9px] text-[var(--muted)] uppercase tracking-widest mt-6">
            New here? 
            <a routerLink="/register" class="text-[var(--brand-dark)] font-black hover:text-[var(--brand-gold)] transition-colors underline decoration-[var(--brand-gold)] underline-offset-4 ml-1">Create Account</a>
          </p>
        </div>
      </div>
      
      <!-- Bottom Branding -->
      <div class="absolute bottom-6 left-0 w-full text-center">
        <p class="text-[8px] uppercase tracking-[0.4em] text-[var(--muted)] opacity-50">© 2024 SkinToneAI · Luxury Fashion Curator</p>
      </div>
    </div>
    <p-toast></p-toast>
  `
})
export class LoginComponent {
  private fb = inject(FormBuilder);
  private authService = inject(AuthService);
  private router = inject(Router);
  private messageService = inject(MessageService);
  readonly ArrowIcon = ArrowRight;
  readonly EyeIcon = Eye;
  readonly EyeOffIcon = EyeOff;
  readonly SparklesIcon = Sparkles;

  showPw = false;
  isLoading = false;
  error = '';
  features = ['AI skin tone analysis', 'Curated outfit recommendations', 'Direct buy links'];

  loginForm: FormGroup = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required]]
  });

  onSubmit() {
    if (this.loginForm.valid) {
      this.isLoading = true;
      this.error = '';
      this.authService.login(this.loginForm.value).subscribe({
        next: () => { this.isLoading = false; this.router.navigate(['/dashboard']); },
        error: (err: any) => { this.isLoading = false; this.error = err.error?.detail || 'Login failed. Please try again.'; }
      });
    }
  }
}

// src/features/auth/Login.jsx
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Mail, Lock, LogIn, ChevronLeft, ArrowRight, Eye, EyeOff, Sparkles } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import Button from '../../components/ui/Button';

/**
 * Login — Soft-pink gradient background, glassmorphism card.
 */
const Login = ({ onBack, onRegister, onLoginSuccess }) => {
  const { login } = useAuth();
  const [formData, setFormData] = useState({ email: '', password: '' });
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      await login(formData.email, formData.password);
      onLoginSuccess?.();
    } catch (err) {
      setError(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      className="min-h-screen w-full flex flex-col items-center justify-center p-6 relative overflow-hidden"
      style={{ background: 'linear-gradient(155deg, #FFF0F3 0%, #FFF4F7 45%, #FFF7F5 100%)' }}
    >
      {/* Depth blobs */}
      <div className="absolute -top-32 -right-24 w-80 h-80 rounded-full bg-rose-100/60 blur-[90px] pointer-events-none" />
      <div className="absolute bottom-0 -left-20 w-72 h-72 rounded-full bg-pink-100/50 blur-[80px] pointer-events-none" />

      <div className="relative w-full max-w-sm space-y-6">
        {/* Top bar */}
        <div className="flex items-center justify-between">
          <button
            id="login-back"
            onClick={onBack}
            className="w-11 h-11 rounded-full bg-white/80 shadow-card border border-rose-100 flex items-center justify-center text-[#6B7280] hover:text-rose-500 hover:border-rose-200 transition-all backdrop-blur-sm"
          >
            <ChevronLeft size={20} />
          </button>
          <h1 className="text-xl font-bold luxury-font text-[#1C1917] tracking-tight">
            Tone<span className="italic opacity-30">Wear</span>
          </h1>
          <div className="w-11" />
        </div>

        {/* Card */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: 'easeOut' }}
          className="rounded-[28px] p-8 md:p-10 space-y-7"
          style={{
            background: 'rgba(255,255,255,0.82)',
            backdropFilter: 'blur(20px)',
            WebkitBackdropFilter: 'blur(20px)',
            border: '1.5px solid rgba(254,205,211,0.45)',
            boxShadow: '0 20px 48px rgba(244,63,94,0.10), 0 4px 16px rgba(0,0,0,0.04)',
          }}
        >
          <div className="text-center space-y-1.5">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-rose-50 border border-rose-100 mb-2">
              <Sparkles size={11} className="text-rose-400" />
              <span className="text-[9px] font-black uppercase tracking-widest text-rose-400">Welcome Back</span>
            </div>
            <h2 className="text-2xl font-bold luxury-font italic text-[#1C1917]">Sign In</h2>
            <p className="text-[10px] uppercase tracking-widest font-bold text-[#9CA3AF]">Access your style identity</p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Email */}
            <div className="relative group">
              <div className="absolute inset-y-0 left-5 flex items-center text-rose-200 group-focus-within:text-rose-400 transition-colors">
                <Mail size={18} />
              </div>
              <input
                id="login-email"
                type="email"
                placeholder="Email Address"
                className="w-full pl-14 pr-6 py-4 rounded-2xl text-sm text-[#1C1917] placeholder:text-[#C4A0A8] outline-none transition-all"
                style={{
                  background: 'rgba(255,241,242,0.6)',
                  border: '1.5px solid rgba(254,205,211,0.5)',
                }}
                onFocus={(e) => { e.target.style.borderColor = '#FB7185'; e.target.style.boxShadow = '0 0 0 3px rgba(251,113,133,0.12)'; }}
                onBlur={(e) => { e.target.style.borderColor = 'rgba(254,205,211,0.5)'; e.target.style.boxShadow = 'none'; }}
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                required
              />
            </div>

            {/* Password */}
            <div className="relative group">
              <div className="absolute inset-y-0 left-5 flex items-center text-rose-200 group-focus-within:text-rose-400 transition-colors">
                <Lock size={18} />
              </div>
              <input
                id="login-password"
                type={showPassword ? 'text' : 'password'}
                placeholder="Password"
                className="w-full pl-14 pr-14 py-4 rounded-2xl text-sm text-[#1C1917] placeholder:text-[#C4A0A8] outline-none transition-all"
                style={{
                  background: 'rgba(255,241,242,0.6)',
                  border: '1.5px solid rgba(254,205,211,0.5)',
                }}
                onFocus={(e) => { e.target.style.borderColor = '#FB7185'; e.target.style.boxShadow = '0 0 0 3px rgba(251,113,133,0.12)'; }}
                onBlur={(e) => { e.target.style.borderColor = 'rgba(254,205,211,0.5)'; e.target.style.boxShadow = 'none'; }}
                value={formData.password}
                onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                required
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute inset-y-0 right-5 flex items-center text-rose-200 hover:text-rose-400 transition-colors"
              >
                {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
              </button>
            </div>

            {error && (
              <div className="p-3.5 rounded-2xl bg-red-50 border border-red-100 text-[10px] text-red-500 font-bold uppercase tracking-wider text-center">
                {error}
              </div>
            )}

            <Button
              id="login-submit"
              variant="rose"
              size="lg"
              className="w-full"
              disabled={loading}
              type="submit"
            >
              {loading ? 'Verifying…' : 'Sign In'}
              {!loading && <LogIn size={16} />}
            </Button>
          </form>

          <div className="text-center">
            <button
              id="login-to-register"
              onClick={onRegister}
              className="text-[10px] uppercase font-bold tracking-[0.2em] text-[#9CA3AF] hover:text-rose-500 transition-colors flex items-center justify-center gap-2 mx-auto"
            >
              Need an account?{' '}
              <span className="text-rose-400 underline underline-offset-4">Register</span>
              <ArrowRight size={12} />
            </button>
          </div>
        </motion.div>

        <p className="text-center text-[9px] uppercase tracking-widest font-bold text-rose-200">
          Secured · Private · Encrypted
        </p>
      </div>
    </div>
  );
};

export default Login;
