// src/features/auth/Register.jsx
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { User, Mail, Lock, UserPlus, ChevronLeft, ArrowRight, Eye, EyeOff, Sparkles } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import Button from '../../components/ui/Button';

/**
 * Register — Matching pink-gradient glassmorphism auth screen.
 */
const Register = ({ onBack, onLogin, onRegisterSuccess }) => {
  const { register } = useAuth();
  const [formData, setFormData] = useState({ name: '', email: '', password: '' });
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      await register(formData.name, formData.email, formData.password);
      onRegisterSuccess?.();
    } catch (err) {
      setError(err);
    } finally {
      setLoading(false);
    }
  };

  const inputStyle = {
    background: 'rgba(255,241,242,0.6)',
    border: '1.5px solid rgba(254,205,211,0.5)',
  };

  const handleFocus = (e) => {
    e.target.style.borderColor = '#FB7185';
    e.target.style.boxShadow = '0 0 0 3px rgba(251,113,133,0.12)';
  };
  const handleBlur = (e) => {
    e.target.style.borderColor = 'rgba(254,205,211,0.5)';
    e.target.style.boxShadow = 'none';
  };

  const baseInput = "w-full py-4 rounded-2xl text-sm text-[#1C1917] placeholder:text-[#C4A0A8] outline-none transition-all";

  return (
    <div
      className="min-h-screen w-full flex flex-col items-center justify-center p-6 relative overflow-hidden"
      style={{ background: 'linear-gradient(155deg, #FFF0F3 0%, #FFF4F7 45%, #FFF7F5 100%)' }}
    >
      {/* Depth blobs */}
      <div className="absolute -top-24 right-0 w-80 h-80 rounded-full bg-pink-100/60 blur-[90px] pointer-events-none" />
      <div className="absolute bottom-0 -left-16 w-72 h-72 rounded-full bg-rose-100/50 blur-[80px] pointer-events-none" />

      <div className="relative w-full max-w-sm space-y-6">
        {/* Top bar */}
        <div className="flex items-center justify-between">
          <button
            id="register-back"
            onClick={onBack}
            className="w-11 h-11 rounded-full bg-white/80 shadow-card border border-rose-100 flex items-center justify-center text-[#6B7280] hover:text-rose-500 hover:border-rose-200 transition-all backdrop-blur-sm"
          >
            <ChevronLeft size={20} />
          </button>
          <h1 className="text-xl font-bold luxury-font text-[#1C1917] tracking-tight">
            Tone<span className="italic opacity-30">Wear</span>
          </h1>
          <div className="w-11" />
        </div>

        {/* Card */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: 'easeOut' }}
          className="rounded-[28px] p-8 md:p-10 space-y-6"
          style={{
            background: 'rgba(255,255,255,0.82)',
            backdropFilter: 'blur(20px)',
            WebkitBackdropFilter: 'blur(20px)',
            border: '1.5px solid rgba(254,205,211,0.45)',
            boxShadow: '0 20px 48px rgba(244,63,94,0.10), 0 4px 16px rgba(0,0,0,0.04)',
          }}
        >
          <div className="text-center space-y-1.5">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-rose-50 border border-rose-100 mb-2">
              <Sparkles size={11} className="text-rose-400" />
              <span className="text-[9px] font-black uppercase tracking-widest text-rose-400">Create Account</span>
            </div>
            <h2 className="text-2xl font-bold luxury-font italic text-[#1C1917]">Start Your Journey</h2>
            <p className="text-[10px] uppercase tracking-widest font-bold text-[#9CA3AF]">Discover your colour story</p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Name */}
            <div className="relative group">
              <div className="absolute inset-y-0 left-5 flex items-center text-rose-200 group-focus-within:text-rose-400 transition-colors">
                <User size={18} />
              </div>
              <input
                id="register-name"
                type="text"
                placeholder="Full Name"
                className={`${baseInput} pl-14 pr-6`}
                style={inputStyle}
                onFocus={handleFocus}
                onBlur={handleBlur}
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                required
              />
            </div>

            {/* Email */}
            <div className="relative group">
              <div className="absolute inset-y-0 left-5 flex items-center text-rose-200 group-focus-within:text-rose-400 transition-colors">
                <Mail size={18} />
              </div>
              <input
                id="register-email"
                type="email"
                placeholder="Email Address"
                className={`${baseInput} pl-14 pr-6`}
                style={inputStyle}
                onFocus={handleFocus}
                onBlur={handleBlur}
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                required
              />
            </div>

            {/* Password */}
            <div className="relative group">
              <div className="absolute inset-y-0 left-5 flex items-center text-rose-200 group-focus-within:text-rose-400 transition-colors">
                <Lock size={18} />
              </div>
              <input
                id="register-password"
                type={showPassword ? 'text' : 'password'}
                placeholder="Create Password"
                className={`${baseInput} pl-14 pr-14`}
                style={inputStyle}
                onFocus={handleFocus}
                onBlur={handleBlur}
                value={formData.password}
                onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                required
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute inset-y-0 right-5 flex items-center text-rose-200 hover:text-rose-400 transition-colors"
              >
                {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
              </button>
            </div>

            {error && (
              <div className="p-3.5 rounded-2xl bg-red-50 border border-red-100 text-[10px] text-red-500 font-bold uppercase tracking-wider text-center">
                {error}
              </div>
            )}

            <Button
              id="register-submit"
              variant="rose"
              size="lg"
              className="w-full"
              disabled={loading}
              type="submit"
            >
              {loading ? 'Creating Account…' : 'Register Now'}
              {!loading && <UserPlus size={16} />}
            </Button>
          </form>

          <div className="text-center">
            <button
              id="register-to-login"
              onClick={onLogin}
              className="text-[10px] uppercase font-bold tracking-[0.2em] text-[#9CA3AF] hover:text-rose-500 transition-colors flex items-center justify-center gap-2 mx-auto"
            >
              Already a member?{' '}
              <span className="text-rose-400 underline underline-offset-4">Sign In</span>
              <ArrowRight size={12} />
            </button>
          </div>
        </motion.div>

        <p className="text-center text-[9px] uppercase tracking-widest font-bold text-rose-200">
          Free Forever · No Credit Card Required
        </p>
      </div>
    </div>
  );
};

export default Register;

// src/app/features/auth/register/register.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { AuthService } from '../../../core/services/auth.service';
import { Toast } from 'primeng/toast';
import { MessageService } from 'primeng/api';
import { LucideAngularModule, ArrowRight, Sparkles } from 'lucide-angular';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, RouterModule, ReactiveFormsModule, Toast, LucideAngularModule],
  providers: [MessageService],
  template: `
    <div class="min-h-screen flex items-center justify-center bg-[var(--surface)] p-6 relative overflow-hidden">
      <!-- Background Decorative Elements -->
      <div class="absolute top-0 left-0 w-full h-full opacity-[0.03] pointer-events-none" style="background-image:linear-gradient(var(--brand-dark) 1px,transparent 1px),linear-gradient(90deg,var(--brand-dark) 1px,transparent 1px);background-size:40px 40px"></div>
      <div class="absolute -top-24 -right-24 w-96 h-96 bg-[var(--brand-gold)] opacity-[0.05] rounded-full blur-3xl"></div>
      <div class="absolute -bottom-24 -left-24 w-96 h-96 bg-[var(--brand-dark)] opacity-[0.05] rounded-full blur-3xl"></div>

      <div class="w-full max-w-sm bg-white rounded-[var(--radius-lg)] shadow-2xl border border-[var(--border)] relative z-10 overflow-hidden animate-slide-up">
        <div class="p-6 sm:p-8">
          <!-- Logo -->
          <div class="flex flex-col items-center gap-2 mb-6">
            <div class="w-10 h-10 bg-[var(--brand-dark)] rounded-2xl flex items-center justify-center shadow-lg">
              <lucide-angular [img]="SparklesIcon" class="w-4 h-4 text-[var(--brand-gold)]"></lucide-angular>
            </div>
            <div class="text-center">
              <span class="text-base font-black tracking-[0.25em] uppercase text-[var(--brand-dark)]">SkinTone</span>
              <span class="text-base luxury-font italic text-[var(--brand-gold)] ml-1">AI</span>
            </div>
          </div>

          <!-- Heading -->
          <div class="text-center space-y-1 mb-5">
            <h1 class="text-xl luxury-font text-[var(--brand-dark)]">Create Account</h1>
            <p class="text-[8px] uppercase tracking-[0.3em] text-[var(--muted)] font-bold">Join the Elite Fashion Community</p>
          </div>

          <!-- Form -->
          <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="space-y-4">
            


            <div class="space-y-1">
              <label class="text-[9px] font-black tracking-[0.2em] uppercase text-[var(--muted)] px-1">Full Name</label>
              <input type="text" formControlName="name" placeholder="E.g. Alexander McQueen" 
                class="w-full bg-[var(--surface)] border-2 border-transparent rounded-[var(--radius-md)] px-5 py-3 text-sm focus:border-[var(--brand-gold)] focus:bg-white transition-all outline-none">
            </div>

            <div class="space-y-1">
              <label class="text-[9px] font-black tracking-[0.2em] uppercase text-[var(--muted)] px-1">Email Address</label>
              <input type="email" formControlName="email" placeholder="your@email.com" 
                class="w-full bg-[var(--surface)] border-2 border-transparent rounded-[var(--radius-md)] px-5 py-3 text-sm focus:border-[var(--brand-gold)] focus:bg-white transition-all outline-none">
            </div>

            <div class="space-y-1">
              <label class="text-[9px] font-black tracking-[0.2em] uppercase text-[var(--muted)] px-1">Password</label>
              <input type="password" formControlName="password" placeholder="Min. 6 characters" 
                class="w-full bg-[var(--surface)] border-2 border-transparent rounded-[var(--radius-md)] px-5 py-2.5 text-sm focus:border-[var(--brand-gold)] focus:bg-white transition-all outline-none">
              
              <!-- Strength indicators -->
              <div *ngIf="registerForm.get('password')?.value" class="flex gap-1.5 mt-2 px-1">
                <div *ngFor="let i of [1,2,3,4]" class="h-1 flex-1 rounded-full bg-[var(--border)] transition-all overflow-hidden">
                   <div class="h-full bg-[var(--brand-gold)] transition-all duration-300" [style.width.%]="pwStrength >= i ? 100 : 0"></div>
                </div>
              </div>
            </div>

            <div *ngIf="error" class="bg-red-50 border border-red-100 rounded-xl px-4 py-3 animate-fade-in">
              <p class="text-[10px] font-bold text-red-600 uppercase tracking-widest text-center">{{ error }}</p>
            </div>

            <button type="submit" [disabled]="registerForm.invalid || isLoading" 
              class="w-full bg-[var(--brand-dark)] text-white rounded-[var(--radius-md)] py-4 text-[11px] font-black uppercase tracking-[0.3em] shadow-xl hover:bg-[var(--brand-dark-soft)] active:scale-[0.98] transition-all disabled:opacity-30 flex items-center justify-center gap-3">
              <i *ngIf="isLoading" class="pi pi-spin pi-spinner"></i>
              <span>{{ isLoading ? 'Processing...' : 'Create My Account' }}</span>
              <lucide-angular *ngIf="!isLoading" [img]="ArrowIcon" class="w-4 h-4"></lucide-angular>
            </button>
          </form>

          <!-- Footer Link -->
          <p class="text-center text-[9px] text-[var(--muted)] uppercase tracking-widest mt-5">
            Already registered? 
            <a routerLink="/login" class="text-[var(--brand-dark)] font-black hover:text-[var(--brand-gold)] transition-colors underline decoration-[var(--brand-gold)] underline-offset-4 ml-1">Sign In</a>
          </p>
        </div>
      </div>
      
      <!-- Bottom Branding -->
      <div class="absolute bottom-6 left-0 w-full text-center">
        <p class="text-[8px] uppercase tracking-[0.4em] text-[var(--muted)] opacity-50">© 2024 SkinToneAI · Luxury Fashion Curator</p>
      </div>
    </div>
    <p-toast></p-toast>
  `
})
export class RegisterComponent {
  private fb = inject(FormBuilder);
  private authService = inject(AuthService);
  private router = inject(Router);
  private messageService = inject(MessageService);
  readonly ArrowIcon = ArrowRight;
  readonly SparklesIcon = Sparkles;
  isLoading = false;
  error = '';

  registerForm: FormGroup = this.fb.group({
    name: ['', Validators.required],
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]]
  });
  get pwStrength(): number {
    const pw = this.registerForm.get('password')?.value || '';
    let s = 0;
    if (pw.length >= 6) s++;
    if (/[A-Z]/.test(pw)) s++;
    if (/[0-9]/.test(pw)) s++;
    if (/[^A-Za-z0-9]/.test(pw)) s++;
    return s;
  }

  onSubmit() {
    if (this.registerForm.valid) {
      this.isLoading = true;
      this.error = '';

      const registerPayload = {
        name: this.registerForm.get('name')?.value,
        email: this.registerForm.get('email')?.value,
        password: this.registerForm.get('password')?.value
      };

      this.authService.register(registerPayload).subscribe({
        next: () => {
          this.messageService.add({ severity: 'success', summary: 'Account Created!', detail: 'Welcome to SkinToneAI!' });
          
          // Auto-login after registration
          const email = this.registerForm.get('email')?.value;
          const password = this.registerForm.get('password')?.value;
          
          this.authService.login({ email, password }).subscribe({
            next: () => {
              this.isLoading = false;
              this.router.navigate(['/upload']);
            },
            error: () => {
              this.isLoading = false;
              this.router.navigate(['/login']);
            }
          });
        },
        error: (err: any) => { 
          this.isLoading = false; 
          this.error = err.error?.detail || 'Registration failed.'; 
        }
      });
    }
  }
}
